### ISSUE TITLE
Should LOCK file be removed when app closes?

### ISSUE THREAD

**Issue by mhkeller** [scriptoLLC/level-session-store#5]
I'm new to leveldb but the presence of a LOCK file is causing issues in another environment. When the app is off, should that file be deleted?

**Comment by toddself** [comment]
it should be removed...however I'm not sure of any life-cycle event I can hook into to know when the express server is shutting down?

I suppose I could attach something to the process `exit` event, however that is supposed to only be synchronous calls and `db.close` is an async method.  Let me do some experimenting with this.

**Comment by mhkeller** [comment]
I generally always run express through nodemon (in dev) or forever (in production), which might have better events to hook on to if that helps. Perhaps if you optionally use one of those methods, you get access to this feature.

**Comment by toddself** [comment]
AFAIK they don't emit events into the software other than standard UNIX signals. 

I will likely just use `process.on('exit')` which should cover all of these use-cases

**Comment by toddself** [comment]
So there's no "right" way to provide this easily. `process.on('exit')` does not allow async methods to run, so the `close()` method is unable to close down access to the DB.

This goes the same for `SIGTERM`, `SIGKILL`, `SIGHUP`, etc.

I could allow the passing in of the server object and attach a listener to  the server `close` event, but that would allow the close method to be called if the server is shutdown with something that causes the `close` event to emit -- I would need to test to see if the `close` event emits on a SIGTERM signal and allows for the async execution of `db.close()`

**Comment by mhkeller** [comment]
What do you think the best strategy is?

**Comment by toddself** [comment]
You could add a process.on exit that calls fs.unlinkSync to remove the lock file. Probably the best bet to be honest.

**Comment by toddself** [comment]
@mhkeller with node being able to do async exit hooks, is this still an issue?  I'd prefer that users remove the LOCK file themselves to prevent issues with me removing it too soon :)

**Comment by mhkeller** [comment]
I haven’t used this in a couple years so I defer to anyone who has recent experience.

**Comment by toddself** [comment]
OK cool closing this then.  Thanks!
